version: "3.8"
services:
  expense-tracker-frontend:
    build:
     context: .
     dockerfile: Dockerfile.prod
    image: expense-tracker-frontend-prod
    container_name: expense-tracker-frontend-prod
    # ports:
    #   - 80:8080 # nginx port 80
    # env_file:
    #   - ./.env