FROM node:18-alpine as react-build

WORKDIR /app 

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:18-alpine

COPY --from=react-build /app/build /app/build

# FROM nginx:1.23.2-alpine

# COPY ../nginx.conf /etc/nginx/nginx.conf
# COPY --from=react-build /app/build /usr/share/nginx/html