/* eslint-disable no-shadow */
/* eslint-disable import/prefer-default-export */
export enum ActionType {
	OPEN_REGISTER = "OPEN_REGISTER",
	HIDE_REGISTER = "HIDE_REGISTER",
	TOGGLE_MINICALENDAR = "TOGGLE_MINICALENDAR",
	LOGOUT_USER = "LOGOUT_USER",
	LOGIN_USER = " LOGIN_USER",
	ADD_INCOME_CATEGORY = "INCOME_CATEGORY",
	ADD_EXPENSE_CATEGORY = "ADD_EXPENSE_CATEGORY"
}