/* eslint-disable no-shadow */
/* eslint-disable import/prefer-default-export */
export enum ActionType {
	OPEN_REGISTER = "OPEN_REGISTER",
	HIDE_REGISTER = "HIDE_REGISTER",
	TOGGLE_MINICALENDAR = "TOGGLE_MINICALENDAR",
	LOGOUT_USER = "LOGOUT_USER",
	LOGIN_USER = " LOGIN_USER",
	ADD_INCOME_CATEGORY = "INCOME_CATEGORY",
	ADD_EXPENSE_CATEGORY = "ADD_EXPENSE_CATEGORY",
	DELETE_CATEGORY = "DELETE_CATEGORY",
	ADD_TRANSACTION_MONTH_FOR_CALENDAR = "ADD_TRANSACTION_MONTH_FOR_CALENDAR",
	ADD_TRANSACTION_MONTH_FOR_DETAIL = "ADD_TRANSACTION_MONTH_FOR_DETAIL",
	ADD_TRANSACTION_MONTH_FOR_INIT = "ADD_TRANSACTION_MONTH_FOR_INIT",
	UPDATE_TRANSACTION_MONTH = 'UPDATE_TRANSACTION_MONTH'
}